Install Nginx 

- hosts: stagingwebserver

vars:
-server_port: 8080

tasks:
-name: install nginx
template: "template here"
notify:
- restart nginx

##changes happend ? it will install again or restart depending on your handler work
handlers:
-name -restart nginx 
service: name: restarted state = nginx

ps waux | grep nguinx 
